### PR TITLE
[resources] update official reconstruction module config file to incl…

### PR DESCRIPTION
**Pull request by yramachers**
…ude Alpha finder and Gamma clustering, resulting in consistency with the Sensitivity module

Please fill in the following details as appropriate for your pull request.
You can leave any entries that aren't relevant blank. If you think the pull request
will need further commits before being ready for review/merge, prepend "WIP:" to
the title.

Changes proposed in this pull request:
Change the official reconstruction configuration file from version 1.0.0 to 1.1.0: 
New features: include Gamma tracking and Gamma clustering and switch on Alpha Finder explicitly.
This configuration file enables to fill all variables created by the Sensitivity module sensibly for further ROOT based analysis.

Does this pull request fix any reported issues?
- Fixes #.

Additional comments or information
----------------------------------
This is a request for the Analysis and Reconstruction groups to review the change to the official reconstruction configuration file. Are the features listed above timely and acceptable for the collaboration? The software development group may change the version scheme or implementation if required. This pull request should start the discussion before being accepted.

### CODE REVIEW

**Comment by pguzowski** [comment]
A cut of 10us for the delayed hits seems slightly too short, and is the reason that tracks in the corner of a cell are being misidentified as delayed.

**Comment by cherylepatrick** [comment]
That's a good point - the file I linked is the one that Lauren is using for her Bi214 study, where she's trying to replicate old distributions from Thibaud (who had that cut at 10µs). I think changing it to 15µs is long enough to stop that from happening - what do other people think?

**Comment by yramachers** [comment]
Pawel, could you find out maybe which drift time limit is appropriate, say from the drift model? At some maximum time, the charge simply doesn't belong to that geiger cell anymore. Is it 15 mus or rather 11 mus or something else?

**Comment by pguzowski** [comment]
The drift model looks a little strange. Here is the base model, showing it is made of two functions (one valid for d < cell radius, and one valid after. There's a discontinuity where they meet. The functions are defined in https://github.com/SuperNEMO-DBD/Falaise/blob/fd289cf9531be22cd5e72d94d3eb60977d685acf/source/falaise/snemo/processing/geiger_regime.cc#L297-L319 where \_t0_ is the time corresponding to the cell radius.

t_v_r_model


This all translates to the following drift-time vs distance calculation that is used in the simulation, and the red width of the plot represents a gaussian smearing sigma. There is a discontinuity around the cell radius (but slightly above, due to the discontinuity in the base model). Above d=2.355cm the drift time is fixed at 10us.
r_v_t
r_v_t_2 2
r_v_t_2 35


I don't know if all this is a bug or not.

Anyway, the maximum drift time in the simulation is 10us + gaussian smearing of sigma=0.6234us

**Comment by yramachers** [comment]
Looks like 13 mus is a good upper limit, roughly 5 sigma out from the 10 mus constant. Let me know if you are happy with 13 mus drift time upper limit and I'll commit a change to the config file on this PR.

**Comment by pguzowski** [comment]
I'm happy with that

**Comment by yramachers** [comment]
With a week of comments passed and the upgrade to Falaise 3.2 coming up soon, I suggest to accept the PR and merge, pending any changes to the file name with version as chosen. Introducing new modules into the pipeline maybe warrants a version 2.0 tag.

**Comment by cherylepatrick** [comment]
@drbenmorgan Did this not make it into Falaise 3.2? I don't seem to have it (again I am wondering if something is up with my installation...)

**Comment by yramachers** [comment]
@cherylepatrick This PR made it into 3.2. The develop branch is currently still identical to version 3.2 and the new file is there in resources/... It is also mentioned as being included in the release notes.

**Comment by cherylepatrick** [comment]
@yramachers Something must be up with my install, in that case, or I am doing something wrong (which might explain how I don't have the fixed vertex generators too).
```
$ ls ~/CadfaelBrew/share/Falaise-3.2.0/resources/config/snemo/demonstrator/reconstruction/
1.0				official_with_visu-1.0.0.conf
official-1.0.0.conf		pipeline
```
Am I looking in the wrong place? It says it's 3.2.0...

**Comment by yramachers** [comment]
I didn't upgrade to a 3.2 install yet since Ben does that here at Warwick and he is off on holiday. The file official-2.0.0.conf is certainly part of the source code on the develop branch at the location you looked at on your local install. So, yes, I reckon something isn't right with the (or your) install.

**Comment by cherylepatrick** [comment]
Yeah, I see it on the develop branch. I don't know if CadfaelBrew has any voodoo as to what it includes? Would be curious to know if anyone has installed using Cadfael and successfully got this change. I did get the curved tracks in the default reconstruction (v1.0.0), so SOMETHING worked...

**Pull request merged**
