### PR TITLE
Feature issue71 -- Add MainWall PMT glass bulk vertex generator for MCC2.0

### LINKED ISSUE #71: New vertex generator asked for PMT glass bulk
Dear dev.

Could you provide a pmt_glass_bulk vertex generator ?
I would like to generate Tl/Bi or K in glass bulk.
 
It should be fine to provide dedicated generators for 5 inch. and 8 inch. PMTs .
The best should be to provide a real map of PMTs per batch production.

Thx,
Yv'

### PR DESCRIPTION
**Pull request by lemiere**
Propose new vtx generator : Main wall PMT Glass (5inches and 8 inches)
We still have to calculate the weighting factors from the effective relative masses....

`generators.pmt_5inch_main_wall_glass_bulk.absolute_weight : real  = 1.0 # To calculate : YL -- may2018
generators.pmt_8inch_main_wall_glass_bulk.absolute_weight : real  = 2.0  # `

Program test is available and work.

- Fixes #71

Next step will be to take nto account PMTs from XWall and GVeto.

### CODE REVIEW

**Comment by lemiere** [comment]
pmt_main_wall_glass_bulk is proposed for uniform main wall contamination.
5 inch absolute weight is calculated using total mass = density * 5"glass volume*nb of 5" PMT
8 inch absolute weight is calculated using total mass = density * 8"glass volume*nb of 8" PMT

pmt_5inch_main_wall_glass_bulk and pmt_8inch_main_wall_glass_bulk can be used for dedicated PMT contamination per PMT size.

**Comment by drbenmorgan** [comment]
Approved, but will await a 👍 from @emchauve before merging!

**Comment by emchauve** [comment]
it works good

pmt

**Comment by drbenmorgan** [comment]
@lemiere, @emchauve now that this is merged, are there any urgent items for MCC2, or would you like a new release (Falaise 3.2.1) at this point?

**Pull request merged**
