### PR TITLE
Feature issue #112 : Add realistic snemo source

### LINKED ISSUE #112: Add realistic source geometry based on Andrea's document
Hi,

For more realistic simulation production, we need to define the real source geometry.
It's imply new geometry, new vertex generator, geant4_control stuff.

### PR DESCRIPTION
**Pull request by lemiere**
Changes proposed in this pull request:
- Add geometry 5.0 to take into account realisitc geometry based on Andrea's documents
- Add materials for each pad
- Add new vertex generator 5.0
      * snemo_full_foil_mass_bulk --> based on source pads mass
      * snemo_full_foil_mass_bulk --> based on source pads Se82 mass
      * snemo_full_source_surface --> based on source pads surface
      * snemo_full_copper_mass_bulk --> based on copper foils mass
      * snemo_full_foil_mass_surface --> based on copper  foils surface
- Add Geant4_control 3.0
- Update all variant to take nto account Realistic/Basic source 
- Propose new URN : urn:snemo:demonstrator:simulation:3.0 --> not the default for now.

Does this pull request fix any reported issues?
- Fixes #112 .

Additional comments or information
----------------------------------

SOON : Materials will change to take into account Se82 enrichment values...

### CODE REVIEW

**Comment by drbenmorgan** [comment]
@lemiere, I've updated the Docker containers for the CI to Bayeux 3.3 and relaunched the build. It looks like the original issue was down to needing the new functionality, but let's see how the CI goes.

**Comment by drbenmorgan** [comment]
@lemiere, I'm going to wait on review of this until #114 is merged. There may be some conflicts between these so better to merge them one at a time, with smallest change first (also bug fix > new feature).

**Comment by drbenmorgan** [comment]
O.k., just relaunched the build to check there are no conflicts with the freshly merged #114, so far so good.

**Comment by drbenmorgan** [comment]
> Propose new URN : urn:snemo:demonstrator:simulation:3.0 --> not the default for now.
> SOON : Materials will change to take into account Se82 enrichment values...

@lemiere, do you want to add these into this PR or do you feel they're better in separate ones? At least the latter feels like it fits in here.

**Comment by lemiere** [comment]
You're right !
I got inputs days ago, so i will propose validated materials.
About the URN, it's trivial. --> as you want

**Comment by cherylepatrick** [comment]
Hi @lemiere - probably won't get around to testing this properly until next week but for now, here are a few comments/questions about the README files:

**Falaise/resources/config/snemo/demonstrator/geometry/5.0/README.rst**

- _Also when enable, we can choose between uniform vertical B-field of mapped field (using Steve Snow's work)._: should that be “uniform OR mapped field”?
- What’s the difference between `mapping/` and `models/` directories?  They both say they are _the directory that contains files dedicated to the building of geometry models_
- When you are describing the various files, you say: _materials/plugin.conf : definitions of specific materials, aliases,_  Should there be something else after that last comma?
- There is a bit that says  `.. code:: sh` What does that mean?
- In the section `Browse and edit geometry variant parameters and options`, what sort of app would you inject a variant profile into and what does that mean? Use it to set the geometry used for flsimulate? Is the geometry used at all by flreconstruct?
- In the section _Display the geometry_, I managed to get the GUI to load, but when I made a change and tried to save it (change Se82 to Nd150), it crashed. I think it might be cos I have the CadfaelBrew version of falaise installed, but as this wanted a built version of Falaise I just went to an old manually built one I had lying around. Maybe the two conflicted? Might be good to include instructions for what you can do if you have the Cadfael version of Falaise? I tried this with an old version so it might be fine with a new one - I'll test it again once I have the new version properly installed.
- The readme talks a lot about geometry 4.1 but is it actually 5.0? In the config files it refers to 5.0.

**Falaise/resources/config/snemo/demonstrator/geometry/5.0/variants/README.rst**

Should there be more in this file? It is very short!

**Falaise/resources/config/snemo/demonstrator/setup/2.0/README.rst**
It’s the setup for 2.0 but the file contents say that it is 1.0. In that file, it also says that the geometry is 4.0;  should it be 5.0? I guess you just copied this from an old version?

**Comment by cherylepatrick** [comment]
**Falaise/resources/config/snemo/demonstrator/simulation/geant4_control/3.0/README.rst**
At the end of this file, in the section _Run Geant4_, it looks as if there should be some examples but the code is missing.

**Comment by cherylepatrick** [comment]
**Falaise/resources/config/snemo/demonstrator/geometry/5.0/README.rst**

There are instructions to run `bxvariant_inspector` and they point at geometry 4.1 when it should be 5.0

**Comment by cherylepatrick** [comment]
Same thing with `bxgeomtools_inspector`. Also it still crashes for me (with the new version) when I try to save and quit:
```
[error:int datatools::library_loader::load(const std::string &, const std::string &, const std::string &, const std::string &, const std::string &):278] datatools::library_loader::load: The 'Falaise' library was not loaded ! DATATOOLS_SYS_NAMESPACE says: 'dlopen(libFalaise.dylib, 1): image not found' !
```

**Comment by lemiere** [comment]
-   “uniform OR mapped field” done

-  difference between mapping/ and models/, I changed the README to explain that mapping contain labeling rules to identify objects define into models dir.

-  .. code:: sh display purpose based on .rst rules

- bxvariant_inspector is used to prepare a dedicated geometry (you can choose mag field ON/OFF, source geometry basic/realistic). The output file (.conf) can be used as an input by flsimulate.

- In the section Display the geometry : for sure, the two conflicted! You should try/test the Falaise using the 'by hand' installation process. The purpose of the README is to test the new geometry tag, so instructions are for developers.
Last remark,  
screenshot_20180903_104153
Geomtry/5.0 provide the source layout option --> Basic or Realistic
Nd150 isotope option is provided only for basic geometry

- Variant directory provide the variant parameters. choice of source materials, thickness... etc... no more...;-)

- /setup/2.0 corrected setup tag 2.0 and geometry tag 5.0

- I will help you about your bxgeomtools_inspector crach.

**Comment by cherylepatrick** [comment]
Note: I am not sure if I inadvertently "approved" more than I have actually tested. I've been away so haven't got round to actually running simulation with the new geometry yet.

**Comment by cherylepatrick** [comment]
Hey, possibly stupid question - should I be able to choose realistic source layout in flsimulate-configure? I can't do that. (Or it's possible that I have made a mistake in the installation...)

**Comment by lemiere** [comment]
You should explicit the new urn which is tag3.0


Envoyé de mon Galaxy S7 Orange
-------- Message d'origine --------De : Cheryl Patrick <notifications@github.com> Date : 05/09/2018  17:54  (GMT+01:00) À : SuperNEMO-DBD/Falaise <Falaise@noreply.github.com> Cc : lemiere <lemiere@lpccaen.in2p3.fr>, Mention <mention@noreply.github.com> Objet : Re: [SuperNEMO-DBD/Falaise] Feature issue #112 : Add realistic snemo source (#113) 
Hey, possibly stupid question - should I be able to choose realistic source layout in flsimulate-configure? I can't do that. (Or it's possible that I have made a mistake in the installation...)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SuperNEMO-DBD/Falaise","title":"SuperNEMO-DBD/Falaise","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/SuperNEMO-DBD/Falaise"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cherylepatrick in #113: Hey, possibly stupid question - should I be able to choose realistic source layout in flsimulate-configure? I can't do that. (Or it's possible that I have made a mistake in the installation...)"}],"action":{"name":"View Pull Request","url":"https://github.com/SuperNEMO-DBD/Falaise/pull/113#issuecomment-418783183"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/SuperNEMO-DBD/Falaise/pull/113#issuecomment-418783183",
"url": "https://github.com/SuperNEMO-DBD/Falaise/pull/113#issuecomment-418783183",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [SuperNEMO-DBD/Falaise] Feature issue #112 : Add realistic snemo source (#113)",
"sections": [
{
"text": "",
"activityTitle": "**Cheryl Patrick**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@cherylepatrick",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"SuperNEMO-DBD/Falaise\",\n\"issueId\": 113,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close pull request",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"SuperNEMO-DBD/Falaise\",\n\"pullRequestId\": 113\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/SuperNEMO-DBD/Falaise/pull/113#issuecomment-418783183"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 355336011\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by cherylepatrick** [comment]
With Yves' new fix today, I can run flvisualize and flreconstruct, and the simulation is running and looks... at least plausible. So far so good! Problem right now: I can't get Things2root to build. Not sure if this is to do with this change - I think it might be a problem with Bayeux 3.3 in general. Will keep testing without it for now.

**Comment by cherylepatrick** [comment]
So I'm finally over all my teething problems and managed to simulate 100k 0nubb events and hit them with the validation tool. I just made a simple module  to extract the x, y, and z position of the vertex, and then compared with a standard file from  the old simulation (source_pads_internal_bulk). z positions agree, which I think we would expect. y positions don't agree, which I think we also expect - do they line up with the foil Se82 percentages we expect? Weirdest one to me is the x position - rather than stopping exactly at a clean edge, it is now tapering off as if the foils are thicker in the middle and thinner at the edges. Is that right? I'll attach the comparison plots and you guys can see what you think. Note that the validation module hasn't been tested by anyone but me either, so I can't promise that it's bug free.

**Comment by cherylepatrick** [comment]
compare_h_vertex_x
compare_h_vertex_y
compare_h_vertex_z

**Comment by lemiere** [comment]
You can try a Y:Z view to show the pad distribution.
Right, there is many pads density and thickness. You can try to estime the ratio of vertex per pad and compare it to the expected value which is relative to the pad masses...
If that's right, I hope that the PR will be accepted. ;-)

**Comment by cherylepatrick** [comment]
Some more distributions for you... here are widths per foil:
vertex_yx
And here is a y-z distribution with the y axis divided into one bin per foil:
vertex_yz
I've also made individual distributions for the x-z vertexes for each individual foil. Not sure if that is going to be too much to upload here? Is there someone more expert than me on what the distributions should be like, who would like to verify if they look good?

**Comment by drbenmorgan** [comment]
Closing as requires reimplementation using new resource layout.

**Pull request closed without merging**
