### PR TITLE
WIP: Realistic Bi207 source calibration

### PR DESCRIPTION
**Pull request by pfranchini**
First changes in order to have a realistic geometry, as per #140.
In this merge:
 - 6 source vertical tracks each with 7 source pads
 - sources in each track have the relative distances taken for the 3D survey
 - I assume the central (4th) source is always in Z=0 for all the 6 tracks
 - I assume that Y is the same within a track
 - all the sources have the same activity (do not know yet how to change it)
 - I have not considered Macko's thesis because the source positions within the envelope is O(0.1mm)
The idea is that a real calibration run will determine the exact positions.

### CODE REVIEW

**Comment by pfranchini** [comment]
I would like @lemiere to have his thoughts on this.

**Comment by drbenmorgan** [comment]
Hi @pfranchini, I've added @lemiere as reviewer for comments. Regards the build, that's all fine according to Travis. The only thing I would suggest is adding a small test to exercise the geometry - say 10 events from the sources run in flsimulate. There are examples of such tests in `programs/flsimulate/tests`.

**Comment by pfranchini** [comment]
Thanks @drbenmorgan, couldn't find how to specify a reviewer.
I have created a test, but I am not sure how can I run it since `make test` is not a valid target.

**Comment by drbenmorgan** [comment]
For the `test` target to be present, you need to configure the build with:

```
$ cmake -DFALAISE_ENABLE_TESTING=ON <otherargs>
```

**Comment by lemiere** [comment]
Hi Paolo, 

I will do it ! 
It's on top of my todo list

**Comment by lemiere** [comment]
Hi,
With the new resources files structures that's a bit messy to me for now...
Can you remind me where I can find the new geometry files for the Bi207 sources ? 
Thx

**Comment by drbenmorgan** [comment]
@lemiere, see the files changed under the "Files changed" tab on this PR (at this link:https://github.com/SuperNEMO-DBD/Falaise/pull/169/files).

Otherwise, the relevant files are:

 resources/snemo/demonstrator/geometry/GeometryModels/source_calibration.geom
 resources/snemo/demonstrator/geometry/GeometryModels/source_model.geom

**Comment by pfranchini** [comment]
I have changed of the carrier/envelope geometry as asked by Yves in #140.

**Comment by lemiere** [comment]
Hi Paolo,

Few remarq : 
The carrier frame you used in the GeometryModel is basic::polyethylen instead of pure copper.
---> To check with Ramon 
The spot looks too big compare to the size of the source frame.
Capture d’écran_2020-02-14_09-17-14
--> To check with Miroslav measurements

For now I do not successfully display the full calibration tracks into the source module...I still have to check it. Probably that's fine...

I simulate Bi207 from calibration source and the vertex distribution looks fine.
Bi207_vertex
Bi207_spot

**Comment by lemiere** [comment]
Hello,

Is there a fresh status for that ?

**Comment by pfranchini** [comment]
Hello, no I haven't touched it. I assume I have to fix the spot/frame size. Is that correct?

**Comment by lemiere** [comment]
Yes!

**Comment by pfranchini** [comment]
Hi @lemiere have modified the spot size according to Macko (~2mm) and the carrier frame material (copper) as in https://github.com/pfranchini/Falaise/commit/5e848c567103aabf7e759833c745dcb2da857f02

**Comment by lemiere** [comment]
Hi All,

Bi207_spot_fixed
full_source
zoom_on_sources

Even the carrier geometry is not exactly the same one as the real one, that's probably good enough. (simulated mass of copper should be close to the real version). Spot looks ok as Miroslav showed. That's ok for me !

**Comment by drbenmorgan** [comment]
Thanks @lemiere! @pfranchini, just to double check before I merge, do you have any further changes to add? If not, we're good to merge!

**Comment by pfranchini** [comment]
Thanks @lemiere for the review. Not sure how to model a polygon, but this can certainly be done later.
Thanks @drbenmorgan I think you can do the merge.

**Pull request merged**
