### PR TITLE
[Falaise/resources] Fix om vertex generator

### PR DESCRIPTION
**Pull request by goliviero**
Fix combined vertexes generator issue
Add weight between back and front in calo scinillator bulks 
Remove activity because of bad typo

### CODE REVIEW

**Comment by goliviero** [comment]
I'm adding a comment to see if the PR will close issues automatically as it is show in this link :
https://github.com/blog/1506-closing-issues-via-pull-requests

Fix issues #14 and #21

**Comment by drbenmorgan** [comment]
@fmauger Could you quickly check this PR and approve or request changes as required please?

**Comment by fmauger** [comment]
Absolute weight for both 8" and 5 " calo bulk vertex generator should be based on the
effective volumes of front/back scintillator parts. This information is not available from
the geometry model itself because we use here a substration shape of whoch the volume 
cannot be computed automatically. However, using simple geometry formula, we can compute 
the effective weights of the generators when combined to make the "calo_8inch_scin_bulk" 
and "calo_5inch_scin_bulk" . See below:

```
[name="calo_8inch_scin_bulk" type="genvtx::combined_vg"]

#@config Vertex generation from the bulk volume of all main calorimeter scintillator blocks with 8'' PMT

generators : string[2] = "calo_8inch_back_scin_bulk" "calo_8inch_front_scin_bulk"

generators.calo_8inch_back_scin_bulk.absolute_weight  : real = 7974.71620749132 # cm3
generators.calo_8inch_front_scin_bulk.absolute_weight : real = 2031.616 # cm3

[name="calo_5inch_scin_bulk" type="genvtx::combined_vg"]

#@config Vertex generation from the bulk volume of all main calorimeter scintillator blocks with 5'' PMT

generators : string[2] = "calo_5inch_back_scin_bulk" "calo_5inch_front_scin_bulk"

generators.calo_5inch_back_scin_bulk.absolute_weight  : real = 9056.702036923 # cm3
generators.calo_5inch_front_scin_bulk.absolute_weight : real = 2031.616 # cm3
```

**Comment by fmauger** [comment]
Is it possible for a validator to modify files in PR22 (change file contents) directly from his/her local branch
used for testing ?

**Comment by drbenmorgan** [comment]
@fmauger, you can checkout the branch, modify, push to your own fork. @goliviero can then add your fork as a remote, and pull the changes onto his branch.

More details in the [Contributing Guide](https://github.com/SuperNEMO-DBD/Falaise/blob/develop/CONTRIBUTING.md#working-with-others)

**Comment by fmauger** [comment]
It is a very heavy procedure for only a few bytes to be changed !!! Tedious and time-consuming !
Is there another way to update a PR directly from the https://github.com/SuperNEMO-DBD/Falaise/pull/22 repo itself or from my own test branch ?

**Comment by drbenmorgan** [comment]
In this specific case, I would just recommend the changes to @goliviero and he can commit and push to the branch. 

In general, code reviews should be handled like paper reviews - suggested/required changes only rather than direct edits by the reviewer.  Since we can share changes in Git, this is best done via the shared branch mechanism described in the [relevant section of the Contribution Guide](https://github.com/SuperNEMO-DBD/Falaise/blob/develop/CONTRIBUTING.md#working-with-others). Yes, the initial setup might seem awkward, but it just comes down to three git commands, `checkout` to get a branch with the PR on, `remote add` to point to your repo, `push` to publish your changes on your repo.

**Comment by drbenmorgan** [comment]
Apologies, accidentally  pushed "Close and comment"... Reopended!

**Comment by fmauger** [comment]
I have create a script where scin block volumes are computed. I will add it later in the resource file tree.
For now the fix seems ok.

**Pull request merged**
