### PR TITLE
WIP: Reconstruction of Bi207 internal conversion electrons

### PR DESCRIPTION
**Pull request by pfranchini**
As suggested by @fmauger in #69, have include the generator (here called `calibBi207`) for the Bi207 calibration sources using the `genbb::time_slicer_generator`.
It works as generator but the reconstruction problem in the abovementioned issue is still open.
Have tried to fiddle with different `time_threshold` and `time_cut` but the electrons produced by internal conversion are still not reconstructed. However, this addition is useful for people playing with it.

Simulation test has been included.

Please have @fmauger as reviewer.

### CODE REVIEW

**Comment by pfranchini** [comment]
@fmauger @lemiere Can you please guys have a look at this? We have involved Miroslav M. in the group in order to extract the Bi207 calibration constants and would be nice using the proper reconstructed data for that. Thanks.

**Comment by emchauve** [comment]
I will test with high stats ASAP

**Comment by emchauve** [comment]
I have generated 1E7 events, it looks good. Just the time threshold must be reduced to 100 ns in order to separate correctly prompt and delayed components. The time cut at 5 s is too low and is removing an important fraction of delayed events, I proposed to increase it to 100 s.  see the attached plot with primary particle time before applying the time_slicer_generator

genbb-Bi207-1e7

I found 2 issues related to Bayeux :
- The vertex generator being independent of genbb, when the genbb's primary event is split into 2 separated events prompt and delayed, they become associated to a different vertex, while they should have the same vertex in theory... probably not a big issue at the end for Bi207 simulation, but we may have to think about it.
- For delayed event, the time_slicer_generator is putting a non-zero time for the primary event (earliest time among all delayed particle time) and subtracting it from each delayed particle time. This makes all particle time seen as "prompt" with respect to the time of the primary event. However this event is still seen as delayed by flreconstruct pipeline, because the final time of calo/tracker hits particle is the sum of `time of primary event + time of particles` !!  We can bypass this issue by forcing a primary event time of delayed event to 0 (easy) OR changing the way that reconstruction is done : by using effective tracker/calo hit time relative to primary event time... (harder ?)

**Review by emchauve — DISMISSED** [review]

**Comment by emchauve** [comment]
It looks we have not merge the Bi207 generator with the time slicer fix!!!

**Comment by fmauger** [comment]
This fix is in Bayeux's code or in a Falaise's config file ?

**Comment by fmauger** [comment]
I have noticed your comment about the vertex issues for prompt-delayed splitted decays. I will have a look ASAP in Bayeux.

**Comment by emchauve** [comment]
> This fix is in Bayeux's code or in a Falaise's config file ?

it is in Falaise, the branch comes from pfranchini repository

**Comment by fmauger** [comment]
So we will see later if we can fix the remaining issue mentionned by @emchauve. At least, let's go for a production trial with this new generator.

**Pull request merged**
