### PR TITLE
fix datatools::kernel::stuff into datatools::stuff to sync with bxcppdev/bayeux 32f2144 commit

### PR DESCRIPTION
**Pull request by emchauve**
Falaise develop is not compiling with Bayeux develop following a recent update on Bayeux init flags

### CODE REVIEW

**Comment by fmauger** [comment]
Hi 

I would adapt this fix a little bit to enable the usage of former versions of Bayeux as well as the new 3.4.4:

In the includes section:

``
#include <bayeux/version.h>
#include <bayeux/bayeux_config.h>
#if BAYEUX_VERSION >= 30404
#pragma message ( "Bayeux version >= 30404" )
#include <bayeux/datatools/datatools_init.h>
#else
#pragma message ( "Bayeux version < 30404" )
#endif
#include <bayeux/datatools/kernel.h>
``

Then the ``app_kernel_init_flags`` function:

``uint32_t app_kernel_init_flags() {
  uint32_t kernel_init_flags = 0;
#if BAYEUX_VERSION >= 30404
  kernel_init_flags |= datatools::init_no_help;
  kernel_init_flags |= datatools::init_no_splash;
  kernel_init_flags |= datatools::init_no_inhibit_libinfo;
  kernel_init_flags |= datatools::init_no_libinfo_logging;
  kernel_init_flags |= datatools::init_no_variant;
  kernel_init_flags |= datatools::init_no_inhibit_variant;
  kernel_init_flags |= datatools::init_no_locale_category;
  kernel_init_flags |= datatools::init_no_inhibit_qt_gui;
  kernel_init_flags |= datatools::init_no_inhibit_urnquery;
#else
  kernel_init_flags |= datatools::kernel::init_no_help;
  kernel_init_flags |= datatools::kernel::init_no_splash;
  kernel_init_flags |= datatools::kernel::init_no_inhibit_libinfo;
  kernel_init_flags |= datatools::kernel::init_no_libinfo_logging;
  kernel_init_flags |= datatools::kernel::init_no_variant;
  kernel_init_flags |= datatools::kernel::init_no_inhibit_variant;
  kernel_init_flags |= datatools::kernel::init_no_locale_category;
  kernel_init_flags |= datatools::kernel::init_no_inhibit_qt_gui;
  kernel_init_flags |= datatools::kernel::init_no_inhibit_urnquery;
#endif
  return kernel_init_flags;
}
``

Otherwise, this fix is ok. 
Cheers

**Comment by drbenmorgan** [comment]
Could we get an update on _which_ Bayeux versions are now being used/required please @emchauve? We don't have capacity to test more than a couple, and need better reporting from upstream on changes...

**Comment by fmauger** [comment]
Version at CCIN2P3 is 3.4.2.
My own devel version is 3.4.4.
So I think we should still support both for a while. That's why I suggest this mod in the PR.

**Comment by drbenmorgan** [comment]
Excellent, thanks @fmauger! LGTM, and I'll go for an update to 3.4.2 as a starting point, can then move to 3.4.4.

**Review by drbenmorgan — APPROVED** [review]

**Pull request merged**
